version: 0.2
phases:
 install:
   runtime-versions:
     docker: 19
 pre_build:
   commands:
     - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
     - REPOSITORY_URI={101234771966.dkr.ecr.us-east-1.amazonaws.com/nodejs-test}
     - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
     - IMAGE_TAG=${COMMIT_HASH:=latest}
 build:
   commands:
     - docker build -t $101234771966.dkr.ecr.us-east-1.amazonaws.com/nodejs-test:latest -f Dockerfile .
     - docker tag $101234771966.dkr.ecr.us-east-1.amazonaws.com/nodejs-test:latest $101234771966.dkr.ecr.us-east-1.amazonaws.com/nodejs-test:$IMAGE_TAG
 post_build:
   commands:
     - docker push $101234771966.dkr.ecr.us-east-1.amazonaws.com/nodejs-test:latest
     - docker push $101234771966.dkr.ecr.us-east-1.amazonaws.com/nodejs-test:$IMAGE_TAG
     - printf '[{"name":"nestjs-graphql","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
 files: arn:aws:s3:::codepipeline-us-east-1-546884881349
